# Name: Anwesh Rawat
# Student ID: 2408634

## Data Importing and Cleaning

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
diabetes_data=pd.read_csv("/content/drive/MyDrive/Concepts and Technologies of AI/Week 7/Dataset/diabetes.csv")
diabetes_data.head(2)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0

In [ ]:
diabetes_data.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [ ]:
diabetes_data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

## Regression Task: Predicting Blood Pressure

In [ ]:
#Dropping the outcome column because it contains binary values
bp_data=diabetes_data.drop(columns=['Outcome'])
bp_data.head(1)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50

In [ ]:
#Creating feature X and label Y
X=bp_data.drop(columns=['BloodPressure']).values
X

array([[  6.   , 148.   ,  35.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  29.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,   0.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  23.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,   0.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  31.   , ...,  30.4  ,   0.315,  23.   ]])

In [ ]:
y=bp_data['BloodPressure'].values
y

array([ 72,  66,  64,  66,  40,  74,  50,   0,  70,  96,  92,  74,  80,
        60,  72,   0,  84,  74,  30,  70,  88,  84,  90,  80,  94,  70,
        76,  66,  82,  92,  75,  76,  58,  92,  78,  60,  76,  76,  68,
        72,  64,  84,  92, 110,  64,  66,  56,  70,  66,   0,  80,  50,
        66,  90,  66,  50,  68,  88,  82,  64,   0,  72,  62,  58,  66,
        74,  88,  92,  66,  85,  66,  64,  90,  86,  75,  48,  78,  72,
         0,  66,  44,   0,  78,  65, 108,  74,  72,  68,  70,  68,  55,
        80,  78,  72,  82,  72,  62,  48,  50,  90,  72,  60,  96,  72,
        65,  56, 122,  58,  58,  85,  72,  62,  76,  62,  54,  92,  74,
        48,  60,  76,  76,  64,  74,  80,  76,  30,  70,  58,  88,  84,
        70,  56,  64,  74,  68,  60,  70,  60,  80,  72,  78,  82,  52,
        66,  62,  75,  80,  64,  78,  70,  74,  65,  86,  82,  78,  88,
        52,  56,  74,  72,  90,  74,  80,  64,  88,  74,  66,  68,  66,
        90,  82,  70,   0,  60,  64,  72,  78, 110,  78,  82,  80,  64,
        74,  60,  74,  68,  68,  98,  76,  80,  62,  70,  66,   0,  55,
        84,  58,  62,  64,  60,  80,  82,  68,  70,  72,  72,  76, 104,
        64,  84,  60,  85,  95,  65,  82,  70,  62,  68,  74,  66,  60,
        90,   0,  60,  66,  78,  76,  52,  70,  80,  86,  80,  80,  68,
        68,  72,  84,  90,  84,  76,  64,  70,  54,  50,  76,  85,  68,
        90,  70,  86,  52,  84,  80,  68,  62,  64,  56,  68,  50,  76,
        68,   0,  70,  80,  62,  74,   0,  64,  52,   0,  86,  62,  78,
        78,  70,  70,  60,  64,  74,  62,  70,  76,  88,  86,  80,  74,
        84,  86,  56,  72,  88,  62,  78,  48,  50,  62,  70,  84,  78,
        72,   0,  58,  82,  98,  76,  76,  68,  68,  68,  68,  66,  70,
        74,  50,  80,  68,  80,  74,  66,  78,  60,  74,  70,  90,  75,
        72,  64,  70,  86,  70,  72,  58,   0,  80,  60,  76,   0,  76,
        78,  84,  70,  74,  68,  86,  72,  88,  46,   0,  62,  80,  80,
        84,  82,  62,  78,  88,  50,   0,  74,  76,  64,  70, 108,  78,
        74,  54,  72,  64,  86, 102,  82,  64,  64,  58,  52,  82,  82,
        60,  75, 100,  72,  68,  60,  62,  70,  54,  74, 100,  82,  68,
        66,  76,  64,  72,  78,  58,  56,  66,  70,  70,  64,  61,  84,
        78,  64,  48,  72,  62,  74,  68,  90,  72,  84,  74,  60,  84,
        68,  82,  68,  64,  88,  68,  64,  64,  78,  78,   0,  64,  94,
        82,   0,  74,  74,  75,  68,   0,  85,  75,  70,  88, 104,  66,
        64,  70,  62,  78,  72,  80,  64,  74,  64,  70,  68,   0,  54,
        62,  54,  68,  84,  74,  72,  62,  70,  78,  98,  56,  52,  64,
         0,  78,  82,  70,  66,  90,  64,  84,  80,  76,  74,  86,  70,
        88,  58,  82,   0,  68,  62,  78,  72,  80,  65,  90,  68,  70,
         0,  74,  68,  72,  70,  74,  90,  72,  68,  64,  78,  82,  90,
        60,  50,  78,  72,  62,  68,  62,  54,  70,  88,  86,  60,  90,
        70,  80,   0,  70,  58,  60,  64,  74,  66,  65,  60,  76,  66,
         0,  56,   0,  90,  60,  80,  92,  74,  72,  85,  90,  78,  90,
        76,  68,  82, 110,  70,  68,  88,  62,  64,  70,  70,  76,  68,
        74,  76,  66,  68,  60,  80,  54,  72,  62,  72,  66,  70,  96,
        58,  60,  86,  44,  44,  80,  68,  70,  90,  60,  78,  76,  76,
        56,  66,  66,  86,   0,  84,  78,  80,  52,  72,  82,  76,  24,
        74,  38,  88,   0,  74,  78,   0,  60,  78,  62,  82,  62,  54,
        58,  88,  80,  74,  72,  96,  62,  82,   0,  86,  76,  94,  70,
        64,  88,  68,  78,  80,  65,  64,  78,  60,  82,  62,  72,  74,
        76,  76,  74,  86,  70,  80,   0,  72,  74,  74,  50,  84,  60,
        54,  60,  74,  54,  70,  52,  58,  80, 106,  82,  84,  76, 106,
        80,  60,  80,  82,  70,  58,  78,  68,  58, 106, 100,  82,  70,
        86,  60,  52,  58,  56,  76,  64,  80,  82,  74,  64,  50,  74,
        82,  80, 114,  70,  68,  60,  90,  74,   0,  88,  70,  76,  78,
        88,   0,  76,  80,   0,  46,  78,  64,  64,  78,  62,  58,  74,
        50,  78,  72,  60,  76,  86,  66,  68,  86,  94,  78,  78,  84,
        88,  52,  78,  86,  88,  56,  75,  60,  86,  72,  60,  74,  80,
        44,  58,  94,  88,  84,  94,  74,  70,  62,  70,  78,  62,  88,
        78,  88,  90,  72,  76,  92,  58,  74,  62,  76,  70,  72,  60,
        70])

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [ ]:
#Test train split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
#Parameters
W=np.zeros(X_train.shape[1])
alpha=0.0001
iteratons=1000

In [ ]:
#Linear regression using scikit
log_reg=LinearRegression()
log_reg.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_pred=log_reg.predict(X_test)
y_pred

array([75.4848195 , 68.83668993, 60.52719422, 62.86508614, 72.57292636,
       81.62836023, 57.82442062, 69.74307749, 73.43209892, 79.89944456,
       72.47537272, 85.59512589, 69.07732379, 72.28634303, 63.43402449,
       70.85223378, 71.10246734, 65.80660337, 68.01828333, 71.787687  ,
       69.95214979, 68.11852471, 83.57868633, 65.60931517, 75.98664278,
       79.5097414 , 65.8741537 , 59.85736909, 73.7577898 , 68.43579006,
       83.0583527 , 82.29139743, 76.11232199, 65.80293445, 77.38587461,
       74.12555534, 98.95496406, 72.37524504, 78.86226469, 68.23289024,
       65.07827121, 74.33909915, 82.27299869, 68.14954622, 58.33967903,
       70.62456428, 83.58911439, 71.73269615, 71.5263937 , 87.25257208,
       61.79748335, 79.72023164, 86.93772812, 61.06214232, 59.89880857,
       64.66469528, 77.87292952, 46.61369157, 70.36638909, 71.48886927,
       78.42849396, 70.7987715 , 71.08150868, 68.10521298, 68.59251906,
       77.97769133, 63.70671968, 75.70845693, 56.56948218, 76.76666194,
       78.28656784, 67.50723703, 71.71094742, 68.23671025, 60.97241091,
       87.577053  , 68.67916099, 69.51407207, 65.72953313, 67.14810945,
       68.28939042, 68.09139954, 67.40856853, 75.30795398, 65.69940022,
       74.66258634, 84.87863756, 69.18566637, 68.96390246, 64.86477418,
       63.16797521, 68.08111115, 46.3153172 , 67.74712391, 72.8854446 ,
       76.0060083 , 69.21382575, 67.93608967, 67.14864658, 67.55474414,
       81.7190926 , 66.86327098, 75.63826669, 73.75211731, 66.70202349,
       73.75512846, 65.91341994, 73.94724961, 67.93032242, 76.65121064,
       63.73482334, 59.76352937, 48.71989276, 82.35749304, 68.19644155,
       68.86299968, 73.26411472, 64.0591936 , 58.44170177, 66.85587189,
       57.4257853 , 75.04960118, 70.60058543, 60.93246366, 60.26403912,
       86.18420226, 51.77101956, 79.36251978, 78.8160822 , 74.08678711,
       64.488306  , 80.52384652, 58.16540725, 75.49411645, 73.19390504,
       63.99521561, 61.05307388, 77.34841887, 81.40609754, 57.45960316,
       63.2783117 , 58.15191699, 62.35624036, 71.26622353, 63.04731758,
       76.01479521, 66.63675976, 57.52373586, 78.46260042, 73.68092243,
       65.93842433, 76.57845343, 69.20126035, 75.62859472])

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
mse=mean_squared_error(y_test,y_pred)
rsq=r2_score(y_test,y_pred)
print(f"Mean Square Error: {mse}\nR-squared: {rsq}")

Mean Square Error: 408.8020357692284
R-squared: 0.1821346640077789

## Classification: For Diabetes

In [ ]:
X2=diabetes_data.drop(columns=['Outcome']).values
X2

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [ ]:
y2=diabetes_data['Outcome'].values
y

array([ 72,  66,  64,  66,  40,  74,  50,   0,  70,  96,  92,  74,  80,
        60,  72,   0,  84,  74,  30,  70,  88,  84,  90,  80,  94,  70,
        76,  66,  82,  92,  75,  76,  58,  92,  78,  60,  76,  76,  68,
        72,  64,  84,  92, 110,  64,  66,  56,  70,  66,   0,  80,  50,
        66,  90,  66,  50,  68,  88,  82,  64,   0,  72,  62,  58,  66,
        74,  88,  92,  66,  85,  66,  64,  90,  86,  75,  48,  78,  72,
         0,  66,  44,   0,  78,  65, 108,  74,  72,  68,  70,  68,  55,
        80,  78,  72,  82,  72,  62,  48,  50,  90,  72,  60,  96,  72,
        65,  56, 122,  58,  58,  85,  72,  62,  76,  62,  54,  92,  74,
        48,  60,  76,  76,  64,  74,  80,  76,  30,  70,  58,  88,  84,
        70,  56,  64,  74,  68,  60,  70,  60,  80,  72,  78,  82,  52,
        66,  62,  75,  80,  64,  78,  70,  74,  65,  86,  82,  78,  88,
        52,  56,  74,  72,  90,  74,  80,  64,  88,  74,  66,  68,  66,
        90,  82,  70,   0,  60,  64,  72,  78, 110,  78,  82,  80,  64,
        74,  60,  74,  68,  68,  98,  76,  80,  62,  70,  66,   0,  55,
        84,  58,  62,  64,  60,  80,  82,  68,  70,  72,  72,  76, 104,
        64,  84,  60,  85,  95,  65,  82,  70,  62,  68,  74,  66,  60,
        90,   0,  60,  66,  78,  76,  52,  70,  80,  86,  80,  80,  68,
        68,  72,  84,  90,  84,  76,  64,  70,  54,  50,  76,  85,  68,
        90,  70,  86,  52,  84,  80,  68,  62,  64,  56,  68,  50,  76,
        68,   0,  70,  80,  62,  74,   0,  64,  52,   0,  86,  62,  78,
        78,  70,  70,  60,  64,  74,  62,  70,  76,  88,  86,  80,  74,
        84,  86,  56,  72,  88,  62,  78,  48,  50,  62,  70,  84,  78,
        72,   0,  58,  82,  98,  76,  76,  68,  68,  68,  68,  66,  70,
        74,  50,  80,  68,  80,  74,  66,  78,  60,  74,  70,  90,  75,
        72,  64,  70,  86,  70,  72,  58,   0,  80,  60,  76,   0,  76,
        78,  84,  70,  74,  68,  86,  72,  88,  46,   0,  62,  80,  80,
        84,  82,  62,  78,  88,  50,   0,  74,  76,  64,  70, 108,  78,
        74,  54,  72,  64,  86, 102,  82,  64,  64,  58,  52,  82,  82,
        60,  75, 100,  72,  68,  60,  62,  70,  54,  74, 100,  82,  68,
        66,  76,  64,  72,  78,  58,  56,  66,  70,  70,  64,  61,  84,
        78,  64,  48,  72,  62,  74,  68,  90,  72,  84,  74,  60,  84,
        68,  82,  68,  64,  88,  68,  64,  64,  78,  78,   0,  64,  94,
        82,   0,  74,  74,  75,  68,   0,  85,  75,  70,  88, 104,  66,
        64,  70,  62,  78,  72,  80,  64,  74,  64,  70,  68,   0,  54,
        62,  54,  68,  84,  74,  72,  62,  70,  78,  98,  56,  52,  64,
         0,  78,  82,  70,  66,  90,  64,  84,  80,  76,  74,  86,  70,
        88,  58,  82,   0,  68,  62,  78,  72,  80,  65,  90,  68,  70,
         0,  74,  68,  72,  70,  74,  90,  72,  68,  64,  78,  82,  90,
        60,  50,  78,  72,  62,  68,  62,  54,  70,  88,  86,  60,  90,
        70,  80,   0,  70,  58,  60,  64,  74,  66,  65,  60,  76,  66,
         0,  56,   0,  90,  60,  80,  92,  74,  72,  85,  90,  78,  90,
        76,  68,  82, 110,  70,  68,  88,  62,  64,  70,  70,  76,  68,
        74,  76,  66,  68,  60,  80,  54,  72,  62,  72,  66,  70,  96,
        58,  60,  86,  44,  44,  80,  68,  70,  90,  60,  78,  76,  76,
        56,  66,  66,  86,   0,  84,  78,  80,  52,  72,  82,  76,  24,
        74,  38,  88,   0,  74,  78,   0,  60,  78,  62,  82,  62,  54,
        58,  88,  80,  74,  72,  96,  62,  82,   0,  86,  76,  94,  70,
        64,  88,  68,  78,  80,  65,  64,  78,  60,  82,  62,  72,  74,
        76,  76,  74,  86,  70,  80,   0,  72,  74,  74,  50,  84,  60,
        54,  60,  74,  54,  70,  52,  58,  80, 106,  82,  84,  76, 106,
        80,  60,  80,  82,  70,  58,  78,  68,  58, 106, 100,  82,  70,
        86,  60,  52,  58,  56,  76,  64,  80,  82,  74,  64,  50,  74,
        82,  80, 114,  70,  68,  60,  90,  74,   0,  88,  70,  76,  78,
        88,   0,  76,  80,   0,  46,  78,  64,  64,  78,  62,  58,  74,
        50,  78,  72,  60,  76,  86,  66,  68,  86,  94,  78,  78,  84,
        88,  52,  78,  86,  88,  56,  75,  60,  86,  72,  60,  74,  80,
        44,  58,  94,  88,  84,  94,  74,  70,  62,  70,  78,  62,  88,
        78,  88,  90,  72,  76,  92,  58,  74,  62,  76,  70,  72,  60,
        70])

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix,precision_score , recall_score , f1_score

In [ ]:
#Splitting thedataset
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.2, random_state=42)

In [ ]:
#Scaling the data
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train2_scaled = scaler.fit_transform(X_train2)
X_test2_scaled = scaler.transform(X_test2)

In [ ]:
#For Logistic Regression
modellogreg=LogisticRegression()
modellogreg.fit(X_train2_scaled,y_train2)

LogisticRegression()

In [ ]:
# Predict on the test data
y_pred = modellogreg.predict(X_test2_scaled)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [ ]:
# Accuracy
accuracy = accuracy_score(y_test2, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

# Confusion Matrix
conf_matrix = confusion_matrix(y_test2, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

#Precision
p=precision_score(y_test2,y_pred)
print(f"Precision Score: {p}")

#Recall
r=recall_score(y_test2,y_pred)
print(f"Recall: {r}")

#f1
f1=f1_score(y_test2,y_pred)
print(f"F1 Score: {f1}")

Accuracy: 75.32%
Confusion Matrix:
[[79 20]
 [18 37]]
Precision Score: 0.6491228070175439
Recall: 0.6727272727272727
F1 Score: 0.6607142857142857